# Generated by Django 3.1.6 on 2022-11-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ID_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='language_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='nationality',
            field=models.IntegerField(null=True),
        ),
    ]
