# Generated by Django 3.1.6 on 2022-11-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0002_auto_20221108_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='is_host',
            field=models.SmallIntegerField(default=0),
        ),
    ]
