# Generated by Django 3.1.6 on 2022-11-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0004_auto_20221109_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_time_pin',
            name='otp_type',
            field=models.CharField(default='login', max_length=25),
        ),
    ]
