# Generated by Django 3.1.6 on 2022-11-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0005_one_time_pin_otp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_icon',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
