# Generated by Django 3.1.6 on 2022-11-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0006_services_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_images',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
