# Generated by Django 3.1.6 on 2022-12-18 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_h_core', '0007_auto_20221115_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_methods',
            fields=[
                ('payment_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=1)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_payment_methods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=1)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_method', to='project_h_core.payment_methods')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
