# Generated by Django 3.1.6 on 2023-03-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0008_payment_methods_user_payment_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostDetails',
            fields=[
                ('host_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_cordinates', models.CharField(blank=True, max_length=80, null=True)),
                ('office_address', models.CharField(blank=True, max_length=80, null=True)),
                ('service_coverage_zone', models.CharField(blank=True, max_length=80, null=True)),
                ('official_certifications', models.CharField(blank=True, max_length=150, null=True)),
                ('number_of_years_practice_speciality', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_years_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('referrals', models.CharField(blank=True, max_length=255, null=True)),
                ('specializations', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_video', models.FileField(blank=True, null=True, upload_to='media')),
                ('languages_spoken', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_images'),
        ),
        migrations.AddField(
            model_name='services',
            name='has_form',
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='Services_sub_categories',
            fields=[
                ('service_sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_sub_category', models.CharField(max_length=50, null=True)),
                ('service_sub_category_fields', models.TextField(blank=True, null=True)),
                ('service_sub_category_icon', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.SmallIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_sub_service_id', to='project_h_core.services')),
            ],
        ),
    ]
