# Generated by Django 3.1.6 on 2023-03-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0009_auto_20230319_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdetails',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_h_core.customers'),
        ),
    ]
