# Generated by Django 3.1.6 on 2023-03-21 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0010_hostdetails_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services_sub_categories',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_sub_service', to='project_h_core.services'),
        ),
        migrations.CreateModel(
            name='Services_sub_category_fields',
            fields=[
                ('service_sub_category_field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=50, null=True)),
                ('has_subs', models.BooleanField(default=0)),
                ('field_options', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.SmallIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_sub_category_field', to='project_h_core.services_sub_categories')),
            ],
        ),
        migrations.CreateModel(
            name='HostReferrals',
            fields=[
                ('host_referral_id', models.AutoField(primary_key=True, serialize=False)),
                ('referral', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_details_referral', to='project_h_core.hostdetails')),
            ],
        ),
    ]
