# Generated by Django 3.1.6 on 2023-03-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0011_auto_20230321_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_sub_categories',
            name='has_subs',
            field=models.BooleanField(default=0),
        ),
    ]
