# Generated by Django 3.1.6 on 2023-03-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0013_auto_20230321_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_sub_categories',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services_sub_category_fields',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
