# Generated by Django 3.1.6 on 2023-03-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0015_auto_20230322_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_sub_category_fields',
            name='subs_display_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
