# Generated by Django 3.1.6 on 2023-03-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0016_services_sub_category_fields_subs_display_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='display_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
