# Generated by Django 3.1.6 on 2023-03-29 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_h_core', '0017_services_display_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('choice', models.CharField(blank=True, max_length=100, null=True)),
                ('preferences', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.SmallIntegerField(blank=True, null=True)),
                ('charge', models.FloatField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_request', to=settings.AUTH_USER_MODEL)),
                ('host_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_service_request', to='project_h_core.hosted_service')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_request', to='project_h_core.payment_methods')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
