# Generated by Django 3.1.6 on 2023-03-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0019_cards_momo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_payment_methods',
            name='payment_method_table_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
