# Generated by Django 3.1.6 on 2023-03-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0020_user_payment_methods_payment_method_table_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_payment_methods',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
