# Generated by Django 3.1.6 on 2023-03-30 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0021_user_payment_methods_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='payment_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_method_request', to='project_h_core.user_payment_methods'),
        ),
    ]
