# Generated by Django 3.1.6 on 2023-04-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0022_requests_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdetails',
            name='host_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hosted_service',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
