# Generated by Django 3.1.6 on 2023-04-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0023_auto_20230405_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosted_service',
            name='service_name',
            field=models.CharField(max_length=50),
        ),
    ]
