# Generated by Django 3.1.6 on 2023-05-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0024_auto_20230405_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_sub_categories',
            name='option_for',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
