# Generated by Django 3.1.6 on 2023-06-12 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_h_core', '0026_requestnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponses',
            fields=[
                ('request_response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.TextField(blank=True, null=True)),
                ('accepted', models.SmallIntegerField(default=2)),
                ('is_first_response', models.BooleanField(default=0)),
                ('active', models.BooleanField(default=1)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_response_user', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_request', to='project_h_core.requests')),
            ],
        ),
        migrations.CreateModel(
            name='RequestNoticeResponses',
            fields=[
                ('request_response_id', models.AutoField(primary_key=True, serialize=False)),
                ('accepted', models.SmallIntegerField(default=2)),
                ('response', models.TextField(blank=True, null=True)),
                ('is_first_response', models.BooleanField(default=0)),
                ('active', models.BooleanField(default=1)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_notice_response_user', to=settings.AUTH_USER_MODEL)),
                ('request_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_request_notice', to='project_h_core.requestnotice')),
            ],
        ),
    ]
