# Generated by Django 3.1.6 on 2023-06-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0027_requestnoticeresponses_requestresponses'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestnoticeresponses',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
