# Generated by Django 3.1.6 on 2023-06-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0028_requestnoticeresponses_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestnotice',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
