# Generated by Django 3.1.6 on 2023-06-13 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0029_requestnotice_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_request', to='project_h_core.payment_methods'),
        ),
    ]
