# Generated by Django 3.1.6 on 2023-08-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0030_auto_20230613_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestnoticeresponses',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestresponses',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterIndexTogether(
            name='requestnoticeresponses',
            index_together={('conversation_id',)},
        ),
        migrations.AlterIndexTogether(
            name='requestresponses',
            index_together={('conversation_id',)},
        ),
    ]
