# Generated by Django 3.1.6 on 2023-08-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0031_auto_20230823_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ID_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
