# Generated by Django 3.1.6 on 2023-09-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0032_auto_20230825_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMenu',
            fields=[
                ('profile_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_number', models.IntegerField()),
                ('menu_name_ENGLISH', models.CharField(max_length=255)),
                ('menu_name_FRENCH', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_name_SPANISH', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_name_PORTUGAL', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_description_ENGLISH', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_description_FRENCH', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_description_SPANISH', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_description_PORTUGAL', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_icon', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=1)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategories',
            fields=[
                ('service_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_category_name_ENGLISH', models.CharField(max_length=255)),
                ('service_category_name_FRENCH', models.CharField(blank=True, max_length=255, null=True)),
                ('service_category_name_SPANISH', models.CharField(blank=True, max_length=255, null=True)),
                ('service_category_name_PORTUGAL', models.CharField(blank=True, max_length=255, null=True)),
                ('service_category_description_ENGLISH', models.CharField(blank=True, max_length=255, null=True)),
                ('service_category_description_FRENCH', models.CharField(blank=True, max_length=255, null=True)),
                ('service_category_description_SPANISH', models.CharField(blank=True, max_length=255, null=True)),
                ('service_category_description_PORTUGAL', models.CharField(blank=True, max_length=255, null=True)),
                ('service_category_icon', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=1)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
