# Generated by Django 3.1.6 on 2023-09-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0033_profilemenu_servicecategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_category_description_ENGLISH',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='service_category_description_FRENCH',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='service_category_description_PORTUGAL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='service_category_description_SPANISH',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='service_category_name_ENGLISH',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='service_category_name_FRENCH',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='service_category_name_PORTUGAL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='service_category_name_SPANISH',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
