# Generated by Django 3.1.6 on 2023-09-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0034_auto_20230911_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemenu',
            name='to_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
