# Generated by Django 3.1.6 on 2023-09-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0037_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProperties',
            fields=[
                ('application_property_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_property_name', models.CharField(max_length=150)),
                ('application_property_name_ENGLISH', models.CharField(blank=True, max_length=150, null=True)),
                ('application_property_name_FRENCH', models.CharField(blank=True, max_length=150, null=True)),
                ('application_property_name_SPANISH', models.CharField(blank=True, max_length=150, null=True)),
                ('application_property_name_PORTUGUESE', models.CharField(blank=True, max_length=150, null=True)),
                ('value', models.CharField(blank=True, max_length=150, null=True)),
                ('active', models.BooleanField(default=1)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
