# Generated by Django 5.0 on 2023-12-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0038_applicationproperties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=150)),
                ('currency_symbol', models.CharField(max_length=5)),
                ('active', models.BooleanField(default=1)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
