# Generated by Django 5.0 on 2023-12-25 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0039_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosted_service',
            name='charge_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_service_currency_id', to='project_h_core.currencies'),
        ),
    ]
