# Generated by Django 3.1.6 on 2024-06-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0040_services_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostreferrals',
            old_name='referral',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='hostreferrals',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hostreferrals',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
