# Generated by Django 3.1.6 on 2024-11-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0041_auto_20240618_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='password_status',
            field=models.IntegerField(default=0),
        ),
    ]
