# Generated by Django 3.1.6 on 2025-01-29 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0042_customers_password_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('selfie', models.ImageField(upload_to='documents')),
                ('id_front_image', models.ImageField(upload_to='documents')),
                ('id_back_image', models.ImageField(upload_to='documents')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_documents', to='project_h_core.hostdetails')),
            ],
        ),
    ]
