# Generated by Django 3.1.6 on 2025-01-29 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0043_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_id_type', to='project_h_core.idtypes'),
        ),
    ]
