# Generated by Django 3.1.6 on 2025-01-31 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0044_auto_20250129_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_documents', to='project_h_core.customers'),
            preserve_default=False,
        ),
    ]
