# Generated by Django 3.1.6 on 2025-02-02 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0045_auto_20250131_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdetails',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_details_service', to='project_h_core.services'),
        ),
    ]
