# Generated by Django 5.1.7 on 2025-06-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0046_auto_20250202_1825'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='requestnoticeresponses',
            new_name='project_h_c_convers_18d012_idx',
            old_fields=('conversation_id',),
        ),
        migrations.RenameIndex(
            model_name='requestresponses',
            new_name='project_h_c_convers_4e2053_idx',
            old_fields=('conversation_id',),
        ),
        migrations.AddField(
            model_name='idtypes',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
