# Generated by Django 5.1.7 on 2026-03-23 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0047_rename_requestnoticeresponses_conversation_id_project_h_c_convers_18d012_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_country', to='project_h_core.countries'),
        ),
    ]
