# Generated by Django 5.1.7 on 2026-03-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_h_core', '0048_remove_documents_host_language_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='host',
        ),
        migrations.AddField(
            model_name='countries',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
